version: 0.2
phases:    
  install:
    runtime-versions:
      dotnet: 3.1
        
  pre_build:
    commands:
#      - echo SLW-App Restore started on `date`
 #     - cd SLW-App
  #    - dotnet restore
   #   - cd ..
      - echo MVC-WebApp
      - dotnet restore


  build:
    commands:
#      - echo SLW-App Build started on `date`
 #     - pwd
  #    - cd SLW-App
   #   - dotnet publish
      - echo MVC-WebApp
    #  - cd ..
      - cd MVC-WebApp
      - dotnet publish
      - dotnet run
#artifacts:
 # type: zip
 # files:
#    - '**/*'
  #   - appspec.yml
   #  - template.yaml
    # - '**/*'
